name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']
    env:
      TZ: UTC
      MAVEN_OPTS: -Duser.timezone=UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build and test (unit + integration)
        run: ./mvnw -ntp -B verify

      - name: Upload application JAR artifact
        if: matrix.java == '21'
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-${{ github.run_id }}
          path: target/*.jar
          if-no-files-found: error

      - name: Upload test reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-and-failsafe-reports-java-${{ matrix.java }}
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**

  package-jar:
    name: Package JAR (skip tests)
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result != 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build (skip tests)
        run: ./mvnw -ntp -B -DskipTests package

      - name: Upload application JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-${{ github.run_id }}-fallback
          path: target/*.jar
          if-no-files-found: error
